# Generated by Django 2.2.5 on 2019-09-23 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="이름")),
                ("score", models.PositiveIntegerField(default=0, verbose_name="점수")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="category"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("start", "도움요청중"),
                            ("progress", "진행중"),
                            ("complete", "완료"),
                        ],
                        default="start",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0, verbose_name="점수")),
                (
                    "main_address",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="메인 주소"
                    ),
                ),
                (
                    "detail_address",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="상세 주소"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="위도"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="경도"),
                ),
                (
                    "occurred_at",
                    models.DateField(blank=True, null=True, verbose_name="발생 시각"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시각"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="request/%Y/%m/%d", verbose_name="이미지"),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="request.Request",
                        verbose_name="의뢰",
                    ),
                ),
            ],
        ),
    ]
