# Generated by Django 2.2.5 on 2019-09-23 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='점수')),
                ('image', models.ImageField(upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='점수')),
                ('main_address', models.CharField(max_length=30, verbose_name='메인 주소')),
                ('detail_address', models.CharField(max_length=50, verbose_name='상세 주소')),
                ('latitude', models.FloatField(blank=True, verbose_name='위도')),
                ('longitude', models.FloatField(blank=True, verbose_name='경도')),
                ('occurred_at', models.DateField(verbose_name='발생 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='request.Category', verbose_name='카테고리')),
            ],
        ),
        migrations.CreateModel(
            name='RequestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='request/%Y/%m/%d', verbose_name='이미지')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='request.Request', verbose_name='의뢰')),
            ],
        ),
    ]
