# Generated by Django 2.2.5 on 2019-09-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20190924_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='police_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.PoliceOffice', verbose_name='경찰서'),
        ),
    ]
