# Generated by Django 2.2.5 on 2019-09-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20190924_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(blank=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_agreed_inform',
            field=models.BooleanField(default=False, verbose_name='정보제공동의'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='제목'),
        ),
    ]
