ㅠ# Generated by Django 2.2.5 on 2019-09-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20190930_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_select',
            field=models.BooleanField(default=False, verbose_name='선택 여부 확인'),
        ),
    ]
